### ISSUE TITLE
Public Docs Checklist

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/fire#47]
- [ ] a contributing document outlining how to contribute to this project
- [ ] quick start section on README (and therefore docs landing page)
- [ ] guiding/design principles explaining _why_ design decisions were made
- [ ] fire HDF5 data format (for developers of fire or other access libraries)
- [ ] #29
